### ISSUE TITLE
mip-cli-boilerplate这个功能是做什么的，

### ISSUE THREAD

**Issue by xiaojinping** [mipengine/mip-cli-boilerplate#7]
你好，我是前端小白。看的不是很懂。
mip-cli-boilerplate 他是做什么的，功能，作用，怎么用。
有没有一个他的完整demo提供参考，
看起来有点像 模板功能 ，比如说类似于vue的模板  例如：index .vue

**Comment by xuexb** [comment]
hi @xiaojinping ，mip-cli-boilerplate 是给 [MIP-CLI](https://github.com/mipengine/mip-cli) 仓库提供的模板，如通过 `mip add index.html mip-fixed` 这样的命令创建页面时使用的页面模板， MIP-CLI 的使用请参考：

- [MIP开发教程(一) MIP-CLI工具安装与环境部署](http://www.cnblogs.com/mipengine/p/mip_cli_1_install.html)
- [MIP开发教程(二) 使用MIP-CLI工具调试MIP网页](http://www.cnblogs.com/mipengine/p/mip_cli_2_page.html)
- [MIP开发教程(三) 使用MIP-CLI工具调试组件](http://www.cnblogs.com/mipengine/p/mip_cli_3_extension.html)
